const dummyData = [
    {
      filename: 'File 1',
      username: 'Jhon',
      rating: 5,
      downloads: 12334,
      timeAgo: '8 days ago',
    },
    {
      filename: 'File 2',
      verified:true ,
      username: 'James',
      rating: 4,
      downloads: 54321,
      timeAgo: '2 days ago',
    },
    {
      filename: 'File 3',
      username: 'Ram',
      rating: 4,
      downloads: 54321,
      timeAgo: '2 days ago',
    },
    {
      filename: 'File 4',
      username: 'Sita',
      rating: 4,
      downloads: 7000,
      timeAgo: '2 days ago',
    },
    {
      filename: 'File 5',
      username: 'Gita',
      rating: 4,
      downloads: 1000,
      timeAgo: '2 days ago',
    },
    {
      filename: 'File 6',
      username: 'Jian',
      rating: 4,
      downloads: 2200,
      timeAgo: '2 days ago',
    },
    {
      filename: 'File 7',
      username: 'Suniyo',
      rating: 4,
      downloads: 5498,
      timeAgo: '2 days ago',
    },
    {
      filename: 'File 8',
      username: 'Sizuka',
      rating: 4,
      downloads: 1200,
      timeAgo: '2 days ago',
    },
    {
      filename: 'File 9',
      username: 'Pikachu',
      verified:true ,
      rating: 4,
      downloads: 1150,
      timeAgo: '2 days ago',
    },
    {
      filename: 'File 10',
      username: 'Hamza',
      rating: 4,
      downloads: 6508,
      timeAgo: '2 days ago',
    },
    {
        filename: 'File 11',
        username: 'Nobita',
        rating: 4,
        downloads: 6555,
        timeAgo: '2 days ago',
      },
    {
      filename: 'File 12',
      username: 'Mohan',
      verified:true ,
      rating: 4,
      downloads: 7860,
      timeAgo: '2 days ago',
    },
    {
      filename: 'File 13',
      username: 'Sohan',
      rating: 4,
      downloads: 1111,
      timeAgo: '2 days ago',
    },
    {
      filename: 'File 14',
      username: 'Anju',
      rating: 4,
      downloads: 2345,
      timeAgo: '2 days ago',
    },
    {
      filename: 'File 15',
      username: 'Anita',
      rating: 4,
      downloads: 1897,
      timeAgo: '2 days ago',
    },
    {
      filename: 'File 16',
      verified:true ,
      username: 'Kamla',
      rating: 4,
      downloads: 2345,
      timeAgo: '2 days ago',
    },
]

export {dummyData} ;